### ISSUE TITLE
Zeros appearing in comparison results panel

### ISSUE THREAD

**Issue by cargopete** [graphops/subgraph-radio#61]
**Describe the bug**
Zeros appearing in the comparison results

**Expected behavior**
Zeros should not be appearing in the comparison results, because if a POI comparison has happened for a given subgraph on a given block, that should mean there is a local attestation for it

**Screenshots**
<img width="674" alt="Screenshot 2023-09-04 at 21 56 05" src="https://github.com/graphops/subgraph-radio/assets/32264020/a0240ded-ab8f-4f3b-bf65-bbe77234a4c8">
<img width="674" alt="Screenshot 2023-09-04 at 21 56 14" src="https://github.com/graphops/subgraph-radio/assets/32264020/00b87ec3-e188-425e-ad81-8d50e462ebc1">

**Comment by hopeyen** [comment]
this one doesn’t make sense to me. locally not found is a variant of comparison result and the behavior is quite literally described in https://github.com/graphops/subgraph-radio/pull/55
