### ISSUE TITLE
Migration handler for JSON → DB store

### ISSUE THREAD

**Issue by cargopete** [graphops/subgraph-radio#69]

**Comment by hopeyen** [comment]
Assume the we have already set up a database with appropriate resolvers to query, add, and remove entries
- depend on implementation in https://github.com/graphops/subgraph-radio/issues/60

#### Migration steps
1. make sure there is a persisted state json file AND no existing data in tables
2. up on loading the cache for persisted state, allow the data to be read and serialized (currently exists [here](https://github.com/graphops/subgraph-radio/blob/55cdff5e03ff81eee1a6a5b7a6ca67779f036026/subgraph-radio/src/config.rs#L144))
3. iterate over the parsed data and insert each entry into the appropriate table
4. delete the persisted state json file upon success of inserting all entries into db
