### ISSUE TITLE
Message validation mechanism shouldn't be shared between features

### ISSUE THREAD

**Issue by cargopete** [graphops/subgraph-radio#95]
**Problem statement**
Currently, the inbound message validation mechanism is set using the `ID_VALIDATION` configuration variable. That validation level is used for all features (POI cross-checking and Subgraph Upgrade pre-sync). 

The default validation level is `indexer`, which is great for the POI cross-checking feature, but it means that all Upgrade intent messages will be discarded, because they're coming from Subgraph Developers (Upgrade intent messages will be accepted only if the level is  `graph-network-account`, or lower). It's worth mentioning that Upgrade pre-sync messages are being tested for whether the sender is the owner of the Subgraph, but that happens after initial validation. 

Users can of course set the validation level to `graph-network-account`, that way they'll accept both POI cross-checking messages from Indexers as usual, as well as Upgrade pre-sync messages from Subgraph Developers. That however would compromise security for the POI cross-checking messages.

**Expectation proposal**
Each feature should have a validation level, adequately corresponding to its function.

**Possible solutions**
1. We set a concrete validation level for Upgrade pre-sync messages to `graph-network-account`, while keeping the `ID_VALIDATION` for all other features (currently just the POI cross-checking one).
2. We allow granular control of the validation level for each feature.

**Comment by cargopete** [comment]
we should use the [SubgraphStaker](https://github.com/graphops/subgraph-radio/blob/2cefd2b90fb71ed7a271497ec04561cb7d061381/test-utils/src/lib.rs#L267) level for this

**Comment by hopeyen** [comment]
To make sure we are on the same page, `SubgraphStaker` should be taking care of this already. 
The identity validation check for `SubgraphStaker` is done on a message type level where the `validity_check` either check for indexer identity for poi messages or check for subgraph ownership for upgrade messages.
More granular control for each message type is a good idea, just not necessary for this release.
